//! A project's metadata fields over the REST client: each getter reads the project
//! document, each setter PUTs that one key version-guarded (a stale version =
//! Error.Conflict), leaving name/colour/layout untouched so the EventUpdated fan-out
//! carries just the change. Bound into `Client` by rest.zig.
const std = @import("std");
const parse = @import("parse.zig");
const payload_mod = @import("payload.zig");

const Client = @import("rest.zig").Client;
const parseProjectStringField = parse.parseProjectStringField;
const parseProjectKeywords = parse.parseProjectKeywords;
const jsonBody = payload_mod.body;

/// Read the active project's current custom name colour ("" = none/theme accent).
pub fn getProjectColor(self: *Client, id: []const u8) ![]u8 {
    const body = try self.getProject(id);
    defer self.gpa.free(body);
    return parseProjectStringField(self.gpa, body, "color");
}

/// PUT a project's custom name colour ("#rrggbb", "" clears), version-guarded (stale → Error.Conflict).
/// Mirrors UpdateProjectRequest{color}: only the colour is sent, riding the EventUpdated fan-out.
pub fn updateProjectColor(self: *Client, id: []const u8, color: []const u8, version: i64) !void {
    const path = try std.fmt.allocPrint(self.gpa, "/projects/{s}", .{id});
    defer self.gpa.free(path);
    const payload = try jsonBody(self.gpa, .{ .color = color, .version = version });
    defer self.gpa.free(payload);
    const body = try self.request(.PUT, path, payload, "application/json");
    self.gpa.free(body);
}

/// Read the active project's blank-image fill colour ("" = not a blank project).
pub fn getProjectBlankColor(self: *Client, id: []const u8) ![]u8 {
    const body = try self.getProject(id);
    defer self.gpa.free(body);
    return parseProjectStringField(self.gpa, body, "blankColor");
}

/// PUT a project's blank fill colour, version-guarded (stale → Error.Conflict). This recolours the
/// stored blank metadata; the raster is regenerated by the front-end that owns the canvas.
pub fn updateProjectBlankColor(self: *Client, id: []const u8, color: []const u8, version: i64) !void {
    const path = try std.fmt.allocPrint(self.gpa, "/projects/{s}", .{id});
    defer self.gpa.free(path);
    const payload = try jsonBody(self.gpa, .{ .blankColor = color, .version = version });
    defer self.gpa.free(payload);
    const body = try self.request(.PUT, path, payload, "application/json");
    self.gpa.free(body);
}

/// Read the active project's free-text description ("" = none).
pub fn getProjectDescription(self: *Client, id: []const u8) ![]u8 {
    const body = try self.getProject(id);
    defer self.gpa.free(body);
    return parseProjectStringField(self.gpa, body, "description");
}

/// PUT a project's free-text description ("" clears), version-guarded (stale → Error.Conflict). Only
/// the description is sent, riding the same EventUpdated fan-out so peers see it live.
pub fn updateProjectDescription(self: *Client, id: []const u8, description: []const u8, version: i64) !void {
    const path = try std.fmt.allocPrint(self.gpa, "/projects/{s}", .{id});
    defer self.gpa.free(path);
    const payload = try jsonBody(self.gpa, .{ .description = description, .version = version });
    defer self.gpa.free(payload);
    const body = try self.request(.PUT, path, payload, "application/json");
    self.gpa.free(body);
}

/// Read the active/named project's current keywords (owned [][]u8; free with freeStrList).
pub fn getProjectKeywords(self: *Client, id: []const u8) ![][]u8 {
    const body = try self.getProject(id);
    defer self.gpa.free(body);
    return parseProjectKeywords(self.gpa, body);
}

/// PUT a project's keywords array, version-guarded (stale → Error.Conflict). Only the keywords are sent
/// (name/colour/layout untouched), riding the same EventUpdated fan-out.
pub fn updateProjectKeywords(self: *Client, id: []const u8, keywords: []const []const u8, version: i64) !void {
    const path = try std.fmt.allocPrint(self.gpa, "/projects/{s}", .{id});
    defer self.gpa.free(path);
    const payload = try jsonBody(self.gpa, .{ .keywords = keywords, .version = version });
    defer self.gpa.free(payload);
    const body = try self.request(.PUT, path, payload, "application/json");
    self.gpa.free(body);
}

/// PUT a project's name, version-guarded (stale → Error.Conflict). Only the name is sent (colour and
/// layout untouched), riding the same EventUpdated fan-out so peers see the rename live.
pub fn updateProjectName(self: *Client, id: []const u8, name: []const u8, version: i64) !void {
    const path = try std.fmt.allocPrint(self.gpa, "/projects/{s}", .{id});
    defer self.gpa.free(path);
    const payload = try jsonBody(self.gpa, .{ .name = name, .version = version });
    defer self.gpa.free(payload);
    const body = try self.request(.PUT, path, payload, "application/json");
    self.gpa.free(body);
}

/// PUT a project's expiration (epoch ms; 0 = keep forever), version-guarded (stale → Error.Conflict).
/// Only the expiry is sent, riding the same EventUpdated fan-out.
pub fn updateProjectExpiry(self: *Client, id: []const u8, expires_at: i64, version: i64) !void {
    const path = try std.fmt.allocPrint(self.gpa, "/projects/{s}", .{id});
    defer self.gpa.free(path);
    const payload = try jsonBody(self.gpa, .{ .expiresAt = expires_at, .version = version });
    defer self.gpa.free(payload);
    const body = try self.request(.PUT, path, payload, "application/json");
    self.gpa.free(body);
}
