# The window: app/ and the model seam's sources, the head of the GUI translation-unit set.

# The full GUI translation-unit set MINUS the entry point (main.cpp), shared between
# the app and the MainWindow GUI e2e test target below so the two never drift.
set(STENCIL_GUI_SOURCES
  src/app/MainWindow.cpp
  src/app/setup/WindowAssemblySignals.cpp
  src/app/events/popover/MainWindowExecPopover.cpp
  src/app/actions/SettingsDialogs.cpp
  src/app/project/flows/ProjectFlows.cpp
  src/app/open/projectThumbs.cpp
  src/app/actions/ActionsBuilder.cpp
  src/app/actions/HotkeyTable.cpp
  src/app/actions/ActionsBuilderData.cpp
  src/app/actions/ActionsBuilderTips.cpp
  src/app/actions/ActionsBuilderWiring.cpp
  src/app/actions/export/ExportMenus.cpp
  src/app/toolbar/ToolbarBuilder.cpp
  src/app/toolbar/ToolbarBuilderHeader.cpp
  src/app/toolbar/ToolbarBuilderRows.cpp
  src/app/toolbar/ToolbarBuilderSections.cpp
  src/app/toolbar/ToolbarBuilderName.cpp
  src/app/toolbar/ToolbarBuilderPage.cpp
  src/app/toolbar/ToolbarBuilderStyle.cpp
  src/app/toolbar/ToolbarBuilderView.cpp
  src/app/actions/MenuBuilder.cpp
  src/app/theme/MainWindowTheme.cpp
  src/app/theme/ThemePainter.cpp
  src/app/theme/ThemePainterIcons.cpp
  src/app/theme/ThemePainterFaces.cpp
  src/app/theme/ThemePainterButtons.cpp
  src/app/remote/DocumentPersistenceFile.cpp
  src/app/remote/StencilFileSync.cpp
  src/app/remote/StencilFileSyncWatch.cpp
  src/app/chat/session/ChatSessionController.cpp
  src/app/chat/session/ChatSessionReply.cpp
  src/app/chat/session/ChatSessionCards.cpp
  src/app/chat/session/ChatSessionClient.cpp
  src/app/chat/session/ChatSessionMirror.cpp
  src/app/chat/session/ChatSessionState.cpp
  src/app/chat/session/ChatSessionPersist.cpp
  src/app/chat/session/ChatAppliers.cpp
  src/app/chat/session/ChatAppliersMedia.cpp
  src/app/chat/session/ChatAppliersSave.cpp
  src/app/events/MainWindowEvents.cpp
  src/app/events/WindowEvents.cpp
  src/app/events/WindowEventsChrome.cpp
  src/app/events/popover/WindowEventsPopover.cpp
  src/app/theme/ThemePainterAccent.cpp
  src/app/open/MainWindowBlank.cpp
  src/app/open/source/SourceOpenerBlank.cpp
  src/app/chat/MainWindowChatDock.cpp
  src/app/chrome/DockChromePlace.cpp
  src/app/chrome/DockChromeCompact.cpp
  src/app/chrome/DockChromeShow.cpp
  src/app/chrome/DockChrome.cpp
  src/app/context/CanvasContextMenu.cpp
  src/app/context/CanvasContextMenuShow.cpp
  src/app/actions/export/ExportMenusVariants.cpp
  src/app/context/CanvasContextMenuRows.cpp
  src/app/events/dropSources.cpp
  src/app/events/MainWindowDnd.cpp
  src/app/chrome/DockChromeDust.cpp
  src/app/view/EditorViewFullscreen.cpp
  src/app/meta/HoverTip.cpp
  src/app/meta/MainWindowImageInfo.cpp
  src/app/events/ArrowPanner.cpp
  src/app/open/source/SourceOpenerLaunch.cpp
  src/app/project/flows/ProjectFlowsMeta.cpp
  src/app/open/source/SourceOpener.cpp
  src/app/project/flows/ProjectFlowsOpenIn.cpp
  src/app/events/popover/PopoverGestures.cpp
  src/app/project/MainWindowProjectClose.cpp
  src/app/project/flows/ProjectFlowsCrud.cpp
  src/app/project/flows/ProjectFlowsColor.cpp
  src/app/project/MainWindowProjectCrud.cpp
  src/app/project/MainWindowProjectLoad.cpp
  src/app/project/MainWindowProjectName.cpp
  src/app/project/ProjectTitleController.cpp
  src/app/project/ProjectTitleControllerEdit.cpp
  src/app/view/MainWindowRefresh.cpp
  src/app/ScriptHost.cpp
  src/app/ScriptHostLaunch.cpp
  src/app/scriptRun.cpp
  src/app/scriptRunOps.cpp
  src/model/ScriptBuffer.cpp
  src/model/ScriptDoc.cpp
  src/app/open/source/SourceOpenerReplace.cpp
  src/app/project/flows/ProjectFlowsServer.cpp
  src/app/project/flows/ProjectFlowsPublish.cpp
  src/app/project/flows/ProjectFlowsLaunch.cpp
  src/app/project/flows/ProjectFlowsSave.cpp
  src/model/lineUnion.cpp          # line union (core lineMerge) and the join cut at the layout caps
  src/app/remote/MainWindowSession.cpp
  src/app/remote/DocumentPersistence.cpp
  src/app/setup/WindowAssembly.cpp
  src/app/setup/WindowAssemblyChat.cpp
  src/app/setup/WindowAssemblyState.cpp
  src/app/setup/WindowAssemblyWidgets.cpp
  src/app/setup/WindowAssemblySwatch.cpp
  src/app/project/copy/ProjectCopy.cpp
  src/app/project/copy/ProjectCopySource.cpp
  src/app/project/copy/ProjectCopySave.cpp
  src/app/project/copy/ProjectCopyOpen.cpp
  src/app/project/copy/ProjectCopyFlow.cpp
  src/app/meta/MainWindowSettings.cpp
  src/app/mainWindowShared.cpp
  src/app/open/MainWindowSource.cpp
  src/app/open/source/SourceOpenerFile.cpp
  src/app/open/source/SourceOpenerMedia.cpp
  src/app/open/source/SourceOpenerLinks.cpp
  src/app/meta/MainWindowState.cpp
  src/app/actions/MainWindowStyleOps.cpp
  src/app/toolbar/StyleControls.cpp
  src/app/view/EditorViewUnits.cpp
  src/app/view/EditorViewAnchor.cpp
  src/app/view/SiblingWindows.cpp
  src/app/view/MainWindowZoom.cpp
  src/app/view/EditorView.cpp
  src/app/context/StayOpenMenu.cpp
  src/app/context/StayOpenMenuKeys.cpp
  src/app/context/StayOpenMenuWalk.cpp
  src/app/logo/LogoHoverFx.cpp
  src/app/logo/LogoHoverFxPaint.cpp
  src/app/logo/LogoStage.cpp
  src/app/logo/LogoStageInput.cpp
  src/app/logo/LogoStagePaint.cpp
  src/app/theme/ThemePainterWebcore.cpp
  src/app/meta/DockZonesOverlay.cpp
  src/app/meta/DataExportController.cpp
  src/app/meta/DataExportImage.cpp
  src/app/remote/RemoteSession.cpp
  src/app/remote/RemoteSyncController.cpp
  src/app/project/ProjectTransferController.cpp
  src/app/project/ProjectTransferImport.cpp
  src/app/open/launchOptions.cpp
  src/io/deepLink.cpp
  src/app/selection/SelectionPanel.cpp
  src/app/selection/SelectionPanelRows.cpp
  src/app/selection/SelectionPanelState.cpp
  src/app/selection/SelectedLineBar.cpp
  src/app/selection/SelectedLineBarRow.cpp
  src/app/selection/SelectedLineBarAlpha.cpp)
