// The facade's types as a file a workspace can hold. Dropped beside a project's JavaScript,
// the editor types `stencil` itself — so a hover names the type instead of `any` — which is
// why the extension steps aside wherever this file is in play.
'use strict';

const { existsSync, mkdirSync, readFileSync, writeFileSync } = require('node:fs');
const { dirname, join } = require('node:path');

const TYPINGS_FILE = 'stencil.d.ts';
const JS_CONFIGS = ['jsconfig.json', 'tsconfig.json'];

// The copy that ships in the .vsix, generated by tools/genTypings.mjs from the app's own types.
const PACKAGED = join(__dirname, '..', '..', 'typings', TYPINGS_FILE);

// A project with no config of its own gets the smallest one that picks the types up.
const JS_CONFIG = `${JSON.stringify({
  compilerOptions: { target: 'es2022', module: 'esnext', checkJs: false, lib: ['es2022', 'dom'] },
  include: ['**/*.js', '**/*.d.ts'],
}, null, 2)}\n`;

const typingsPath = (folder) => join(String(folder ?? ''), TYPINGS_FILE);

const installedIn = (folder) => !!folder && existsSync(typingsPath(folder));

const hasJsConfig = (folder) => JS_CONFIGS.some((name) => existsSync(join(String(folder ?? ''), name)));

/* Writes the types, and a jsconfig only where the project has none — one that does is the
 * user's, and may deliberately include or exclude what this file lands beside. */
const install = (folder) => {
  const target = typingsPath(folder);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, readFileSync(PACKAGED, 'utf8'));
  const config = hasJsConfig(folder) ? '' : join(folder, JS_CONFIGS[0]);
  if (config) writeFileSync(config, JS_CONFIG);
  return { typings: target, config };
};

module.exports = { JS_CONFIG, JS_CONFIGS, PACKAGED, TYPINGS_FILE, hasJsConfig, install,
  installedIn, typingsPath };
