// Writes the op-plan corpus's GENERATED half under common/fixtures/llm/opPlan/generated/: the
// mechanical cases derived from opRegistry.json (opPlanCases.mjs), the normalized golden core/opplan
// is byte-compared against (opPlanGoldens.mjs), and the grammar + number probes (opPlanProbes.mjs).
// freshness.json holds the sha256 of every input and output; opPlanFixtures.test.js checks it.
// Usage: node tools/genOpPlanFixtures.mjs [--check]   (--check: exit 1 if stale, write nothing)
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { generate } from './opPlanCases.mjs';
import { checkOracle, normalized, renderNormalized } from './opPlanGoldens.mjs';
import { grammarProbes, numberCases } from './opPlanProbes.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const COMMON = path.join(HERE, '..', '..', 'common');
const OP_PLAN = path.join(COMMON, 'fixtures', 'llm', 'opPlan');
const REGISTRY = path.join(COMMON, 'config', 'llm', 'opRegistry.json');
const HAND = path.join(OP_PLAN, 'cases.json');
const ORACLE = path.join(OP_PLAN, 'oracle', 'inputs.json');
const OUT_DIR = path.join(OP_PLAN, 'generated');
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');

export { generate };

export const render = (cases) => JSON.stringify({
  $schema: 'one entry per fixture, the shape of ../_schema.md; GENERATED by browser/tools/genOpPlanFixtures.mjs from opRegistry.json — do not edit, run `npm run gen-fixtures`',
  cases,
}, null, 1) + '\n';

// A header object plus one compact row per line under `key`, so a diff names the rows it moves.
const rows = (head, key, list) => {
  const top = JSON.stringify(head, null, 1).replace(/\n}$/, '');
  return `${top},\n "${key}": [\n${list.map((r) => `  ${JSON.stringify(r)}`).join(',\n')}\n ]\n}\n`;
};

// Every generated file's text, keyed by its name under generated/.
export const build = () => {
  const registryBytes = readFileSync(REGISTRY);
  const handBytes = readFileSync(HAND);
  const oracleBytes = readFileSync(ORACLE);
  const registry = JSON.parse(registryBytes.toString('utf8'));
  const oracle = JSON.parse(oracleBytes.toString('utf8')).cases;
  checkOracle(registry, oracle);
  const generated = generate(registry);
  const probes = grammarProbes(registry);
  const files = {
    'cases.json': render(generated),
    'normalized.json': renderNormalized(normalized(registry, [
      { source: 'hand', cases: JSON.parse(handBytes.toString('utf8')).cases },
      { source: 'generated', cases: generated },
      { source: 'oracle', cases: oracle },
    ])),
    'grammarProbes.json': rows({
      $schema: 'GENERATED by browser/tools/genOpPlanFixtures.mjs — [probe, [the registry regexes it matches under JS RegExp.test]]; core/opplan/planGrammars matches them by hand',
      regexes: probes.regexes }, 'probes', probes.probes),
    'numbers.json': rows({
      $schema: 'GENERATED by browser/tools/genOpPlanFixtures.mjs — [IEEE-754 bits as hex, JS String(x)]; core/json/jsNumber jsNumberToString must agree' }, 'cases', numberCases()),
  };
  const digests = { registry: sha256(registryBytes), hand: sha256(handBytes), oracle: sha256(oracleBytes) };
  for (const [name, text] of Object.entries(files)) digests[name.replace('.json', '')] = sha256(text);
  files['freshness.json'] = `${JSON.stringify({
    $schema: 'GENERATED by browser/tools/genOpPlanFixtures.mjs — sha256 of every input (registry, hand, oracle) and every generated file',
    ...digests,
  }, null, 1)}\n`;
  return files;
};

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const files = build();
  if (process.argv.includes('--check')) {
    const stale = Object.entries(files).filter(([name, text]) => {
      const file = path.join(OUT_DIR, name);
      return !existsSync(file) || readFileSync(file, 'utf8') !== text;
    });
    if (stale.length) {
      console.error(`stale: ${stale.map(([n]) => n).join(', ')} in ${OUT_DIR} — run npm run gen-fixtures`);
      process.exit(1);
    }
    console.log('generated corpus is fresh');
  } else {
    mkdirSync(OUT_DIR, { recursive: true });
    for (const [name, text] of Object.entries(files)) writeFileSync(path.join(OUT_DIR, name), text);
    console.log(`wrote ${Object.keys(files).join(', ')} under ${OUT_DIR} (${JSON.parse(files['cases.json']).cases.length} cases)`);
  }
}
