// The op-plan golden: every corpus case walked by the JS reference (js/llm/plan/parser.js) for
// every surface that runs core/opplan, as the exact JSON core must emit. Surfaces with the same
// output share one entry. genOpPlanFixtures.mjs writes it as generated/normalized.json.
import { createSchema } from '../js/llm/plan/opSchema.js';
import { walkPlan } from '../js/llm/plan/parser.js';
import COLOR_NAMES from '../../common/config/colorNames.json' with { type: 'json' };

// The surfaces whose validator is core/opplan (the browser walks its JS twin, the reference).
export const CORE_SURFACES = Object.freeze(['browser', 'desktop', 'cli', 'pystencil', 'bot', 'mcp']);

// core's parseColor over a name the CSS_NAME grammar already admitted: ASCII case-folded.
export const knownColor = (name) => {
  const k = name.replace(/[A-Z]/g, (c) => c.toLowerCase());
  return k === 'transparent' || Object.hasOwn(COLOR_NAMES, k);
};

// A case's text as a model reply arrives — UTF-8 bytes decoded by TextDecoder, so a lone
// surrogate or a malformed byte is already U+FFFD. `parts` is [[chunk, times], …] concatenated.
const utf8 = new TextDecoder('utf-8', { ignoreBOM: true });
export const caseText = (c) => {
  if (c.inputBase64 != null) return utf8.decode(Buffer.from(c.inputBase64, 'base64'));
  const text = c.parts ? c.parts.map(([s, n]) => s.repeat(n)).join('')
    : typeof c.input === 'string' ? c.input : JSON.stringify(c.input);
  return utf8.decode(new TextEncoder().encode(text));
};

// The result document as core writes it: a lone surrogate in a string comes out as U+FFFD.
export const resultJson = (r) => JSON.stringify(r, (k, v) => (typeof v === 'string' ? v.toWellFormed() : v));

export const verdictOf = (r) => (r.status === 'invalid' ? 'invalid' : 'valid');

const surfacesFor = (registry, profiles) => CORE_SURFACES.filter(
  (s) => profiles.includes('all') || profiles.includes(registry.$meta.surfaceProfiles[s]));

// sets: [{ source, cases }] — the hand-written, generated and oracle bundles, in that order.
export const normalized = (registry, sets) => {
  const schemas = Object.fromEntries(CORE_SURFACES.map((s) => [s, createSchema(registry, s, { knownColor })]));
  const cases = [];
  for (const { source, cases: list } of sets) {
    for (const c of list) {
      const groups = new Map();
      const text = caseText(c);
      for (const s of surfacesFor(registry, c.profiles || ['all'])) {
        const json = resultJson(walkPlan(schemas[s], text));
        if (!groups.has(json)) groups.set(json, []);
        groups.get(json).push(s);
      }
      cases.push({ name: c.name, source, results: [...groups].map(([json, surfaces]) => ({ surfaces, json })) });
    }
  }
  return cases;
};

// The oracle inputs carry the verdict the JS reference decided; a drifted one fails the build.
export const checkOracle = (registry, oracle) => {
  const schema = createSchema(registry, 'browser', { knownColor });
  const drift = oracle.filter((c) => verdictOf(walkPlan(schema, caseText(c))) !== c.expect).map((c) => c.name);
  if (drift.length) throw new Error(`oracle verdicts drifted from the JS reference: ${drift.join(', ')}`);
};

export const renderNormalized = (cases) => `${JSON.stringify({
  $schema: 'GENERATED by browser/tools/genOpPlanFixtures.mjs — per case, the exact result JSON core/opplan emits (js/llm/plan/parser.js is its twin), grouped by the surfaces that share it; do not edit',
  surfaces: CORE_SURFACES,
  cases,
}, null, 1)}\n`;
